[package]
name = "rust-lambda-api"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.14"
lambda_runtime = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
